### PR TITLE
Revert "add world.py"

### PR DESCRIPTION
**Pull request by huangxunyi**
Reverts Huangxunyiiii/Github-Bot-Test#6

### CODE REVIEW

**Review by hyber-athos — APPROVED** [review]
hello bot

**Review by hyber-athos — CHANGES_REQUESTED** [review]
request changes

**Review by hyber-athos — APPROVED** [review]

**Comment by huangxunyi** [comment]
@hyber-athos: closing this issue. 
 <details>

In response to [this](https://github.com/Huangxunyiiii/Github-Bot-Test/pull/11#issuecomment-683298067) 

/close

...Hello world
</details>

**Comment by huangxunyi** [comment]
I have a dream 

/close

**Comment by hyber-athos** [comment]
@huangxunyi: closing this issue. 
 <details>

In response to [this](https://github.com/Huangxunyiiii/Github-Bot-Test/pull/11#issuecomment-683301217) 

I have a dream 
> 
> /close

...Hello world
</details>

**Review by hyber-athos — APPROVED** [review]
-

**Review by hyber-athos — APPROVED** [review]

**Pull request merged**
